DROP DATABASE URBANFLOW;
CREATE DATABASE URBANFLOW_DB;

CREATE SCHEMA URBANFLOW_DB.BRONZE;
CREATE SCHEMA URBANFLOW_DB.SILVER;
CREATE SCHEMA URBANFLOW_DB.GOLD;

SELECT CURRENT_ACCOUNT();  -- WS37517
SELECT CURRENT_REGION();    -- AWS_AP_SOUTHEAST_7